services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fullcycle
    networks:
      - fc-node
  
  app:
    container_name: app
    build: .
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s node index.js
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mysql
    networks:
      - fc-node

  nginx:
    image: nginx:1.15.0
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - fc-node
    depends_on:
      - app
    ports:
      - 8080:80

networks:
  fc-node:
    driver: bridge